### ISSUE TITLE
[suggestion] add support for curseforge://install links

### ISSUE THREAD

**Issue by burtek** [gorilla-devs/GDLauncher#1055]
**Is your feature request related to a problem? Please describe.**
While on https://www.curseforge.com/minecraft (either in a mod or resourcepack category), user can click install button (see below) to have SF cleint install that mod/resoursepack. It would be nice for GDL to also support those links.

![image](https://user-images.githubusercontent.com/2940958/130779534-b4488455-f809-475c-821a-93cf70c1cf29.png)

**Describe the solution you'd like**
GDL should register for curseforge://install links (i.e. curseforge://install?addonId=301608&fileId=3347453), should show prompt for selecting which instance to add that piece to and then:
 - if it's a mod, add it to selected instance
 - if it's a resoursepack, just download it to instance's folder

**Comment by Eskaan** [comment]
We won’t register events on the Curseforge App, because it
- Could cause problems whit Curseforge App also trying to open the things
- Probably won’t even work because it’s related to the App name
- Probably cause Copyright or law problems ( Because we abuse their Name and Request)

Backed by @killpowa and @hypherionmc

**Comment by burtek** [comment]
fair enough, I agree with those arguments.
