### ISSUE TITLE
Privacy Policy update mentions data collection and opt out, yet isn't in the settings?

### ISSUE THREAD

**Issue by MechanosG** [gorilla-devs/GDLauncher#1068]
I realize this is an unpopular subject, and 3 out of 4 people simply don't care.  But I've been using GDLauncher for a while, under the impression that it was a better alternative to Curseforge/Overwolf, in part because Overwolf has been known to take part in data collection in the past, which concerned a lot of people.  After a several month hiatus, I launched GDLauncher today to find an update, along with mentions of the privacy policy.

So I check it out..  and it flat out says GDLauncher collects data for it's partners, and will save copies of said data, even if you request it be deleted, if it serve's the partner's purposes.  It even further outlines that said data is only restricted in use, if a law forbids said use, even going so far to say that it ignores Do Not Track browser features on the technicality that tracking is not the same as collecting information.  This is super sketchy.  Like, about as bad as privacy policies get.

(Before anyone freaks out and starts making tin foil hat jokes, or acting like they simply don't care and no one else should either, I realize much of this data "probably" doesn't include anything "important", and isn't usable to most people.  But I also realize that data wouldn't be worth anything, if it had nothing of importance to it.  Aka, seemingly anonymous data points can be merged into something identifiable and used for marketing purposes, politics, or worse.  Search Surveillance Capitalism if you need a better explanation.)

Anyway, moving on, the privacy policy mentions "opting out", yet provides no means to do so.  Did I miss a setting to opt out somewhere?  All I could find was a contact email which obviously no one is going to use.

I absolutely want to opt out on GDLauncher collecting and retaining any information it doesn't need, and am formally suggesting there be a setting for this.  Otherwise, this is just another program that privacy advocates have to drop.

**Comment by huantianad** [comment]
From what I've heard they'll be adding the opt out switch sometime later.\
I 100% agree that the privacy policy is somewhat concerning

**Comment by blarfoon** [comment]
This will be the last time I go over this subject. As an open source project we have a really limited amount of resources. Some services such as google analytics are really fast to set up and are completely free to use. Obviously they somehow use your data for their own purposes but most “safe” alternatives out there which don’t use your data cost around 4k to 10k usd per month for our amount of users. You can clearly see that as an open source software we cannot afford that kind of expenses nor do we have time to develop our own in-house solution.

Solutions such as analytics are needed for me to be able to forecast the network traffic I’ll be receiving in the future as well as other insights on how people use the product, thus I am able to improve lacking features.

Another reason for the new privacy policy is that we are working on a lot of custom features which will require storing some data or will work with other external tools which we don’t have control over. In order to use these features we need to have a privacy policy.

My solution as suggested before in another issue is to add an “off the grid” mode. It will disable all our custom apis switching to official ones where possible (login for example) and will disable the features where this is not possible (such as auto updates). This will disable all tracking features but will give somewhat limited functionalities.

**Comment by MechanosG** [comment]
Alright.  So what I gather is..  you don't want to go without analytics, even though lots of other (open source) software does.  Your reasoning is you want or need affordable/free analytics due to networking costs, and letting Google or anyone else have the data is a required sacrifice (that you don't have to make).  Your suggested "solution", is to gimp the software (unless I'm taking "very limited functionalities" too broad) for anyone that wants to opt out?  Or if I'm taking that too broadly or the wrong way, what functionality would specifically be lost?  Like, what does GDLauncher even do that's extra and requires this extra networking, that official APIs can't do?  Why isn't the official API the default to begin with, if the custom API comes with so much cost?  Or is tracking users the main goal of the custom API?

Look, I'm trying to understand your point of view.  But you've obviously taken a stance that you "need" those analytics, and are willing to let everyone else take the hit to get them.  But if GDLauncher just turns into another Overwolf, then what is the point?  Are you going to add ads that telephone home next, to cover some random cost?  There are alternatives like MultiMC that AFAIK are still privacy friendly, and don't even have/require a privacy policy.

https://creativerly.com/google-analytics-alternatives/ None of these are options?  At least 1 is free and many seem pretty cheap.

**Comment by blarfoon** [comment]
Currently aside from g analytics, we don't do much that tracks the user. The privacy policy and ToS I added are for future features. The only decent alternatives are not even in the list you sent, most of those options either suck completely or cost a fortune. The only real alternative we have is mixpanel which comes free up to 100k MAU but it takes a lot more time to be implemented and we are getting terribly close to that amount of users, after that we will need to pay a whopping 10k $ a month.

`you don't want to go without analytics`:  Partially true. I simply don't want to be blind and not know what's going on with the app, what version is mostly used, what screen size is mostly used, and so on. All this information help me make more thoughtful decisions to improve the product. All of them are anonymous and cannot be tracked down to a single specific user. Moreover, some future features which I can't disclose at this time will require tracking because of their nature.

`what does GDLauncher even do that's extra and requires this extra networking, that official APIs can't do?`: A lot of things to be honest. Starting with Mojang messing up their JSON files and not including experimental snapshots (which a lot of people want to play). To be able to provide that we need custom services to host the data. Another example is curseforge's APIs which will soon be deprecated in favor of authenticated services. In order to continue to support them, we will need custom services to interface the end-user with their APIs. These are just a few examples but there are a lot more.

`But you've obviously taken a stance that you "need" those analytics`: As I said I don't necessarily need those analytics but in order to provide a better product and some specific features, I need data on how people use our product and the average traffic we should expect at all time. Opposing to overwolf we will always give you the choice of opting out but it will obviously come at a cost. You can't expect us to just get rid of all analytics and not know what's going on with the app, whether the auto-updater works or not, whether a feature we shipped is not being used for whatever reason. I was recently able to track down a HUGE waste of network requests using our analytics which I would have never been able to track otherwise (https://github.com/gorilla-devs/GDLauncher/commit/422f9caf17969d801abf96592b711fdd236baa93)

Moreover, analytics is just one of the places where we will track some kind of information from the user. Third-party services such as Curseforge, FTB, Microsoft, Mojang, Github, and Forge track your data when making API requests or during other procedures. If you're really into privacy you should probably not use any of them.

I completely understand your request but making the app completely track-free means providing a far worse product without the option to monitor app updates, current, and past traffic as well as features usage.
As I said, you'll be free to opt-out from all our own features that require data storage or tracking and you will not be tracked in any way but by doing so you will also not be able to use some features which are expensive for us or are simply not possible to provide without some kind of cloud data storage.

I hope this answers your question but if not, feel free to let me know!

**Comment by MechanosG** [comment]
Using analytics for a "better product" is the excuse that basically..  all the data harvesting companies use.  It's hard to take that at face value, when "Surveillance Capitalism" exists and continues to grow, and companies are starting to actually be called out on it.  It's worth actually looking it up btw, as I can't really do the argument justice.  There are reason's why Google's service is "free".

Back to the topic, most of the time you can get an idea of what your software is doing by just testing it yourself and following bug reports.  That's how the majority of it was done before analytics and telemetry became so mainstream.  For example, you don't need to know exactly what features are used to what exact amounts..  you can get a pretty good idea by testing yourself, having friends/colleagues test it out, then asking your users about it.  They will be more than willing to tell you what they like and don't like, at their disclosure.  It's not like there's a shortage of Minecraft players.  If random users don't want to share, then you shouldn't force it - people aren't math problems.  This whole idea that it's okay to forcefully take usage data from people, to try and fine tune software, is honestly quite obnoxious and self entitled (and often illegal as far as non-software comparisons are concerned).

As far as networking goes, you can run your client locally and monitor network traffic, then deduce from your own testing that something may be happening.  Or pay attention to how often certain functions are getting called.  You don't need full analytics to do that..  it's just convenient because suddenly all your users become unwilling reporting mechanisms in real world scenarios.

In a perfect world, no one would care about your analytics.  Every GDLauncher user wants a better GDLauncher.  The real problem isn't that you're wanting to track things to keep an eye on stuff.  The problem is going through a company like Google, and the lack of legal protections to guideline what can be taken, how it can be used, and having to blindly trust that people aren't abusing anything.  Especially with that super sketchy all encompassing Privacy Policy.  Not everyone is a programmer, and even the ones that are, likely don't want to go delving into the source of every piece of software (assuming the source is even visible) to make sure information that isn't needed, isn't being pulled.  That won't tell the user what the information is being used for and who it's getting passed along to either.  So the safest/easiest best for anyone not wanting to get involved in all this data crap, is just just avoid anything that deals with these big companies, and avoid data collection in general.

Anyway, I've been at this long enough to know that you can't convince people that don't care about the topic, and you probably disagree with my assessment of debugging and adding/tweaking features without analytics.  The responsible thing to do, is to not subject your users to this.  Instead you're prioritizing productivity.  So once the full opt-out is provided, I may use GDLauncher again.  For now, I'll just keep an eye on things and use MultiMC instead.

**Comment by blarfoon** [comment]
1) `Using analytics for a "better product" is the excuse that basically.. all the data harvesting companies use`: I don't care what other people say or do. We do what we need to do in order to provide a better service to our community. We don't "harvest" any data. We track your app usage in an anonymous way. Nobody has ever been called out for doing this...

2) `There are reason's why Google's service is "free"`: That is very true and I already said I am looking into possible alternatives for the future, also because google analytics is basically garbage as soon as you need more specific analytics queries.

3) `Back to the topic, most of the time you can get an idea of what your software is doing by just testing it yourself and following bug reports`: This is absolutely wrong. The way I use the app is completely different from how other people use the app. I am a completely different target from the average user and there are multiple targets. Without analytics, I won't be able to tell whether or not a feature is used or not and how I can improve it. 

4) `you don't need to know exactly what features are used to what exact amounts..`: This is partially true. I don't need exact amounts in fact I can also take a percentage of our userbase and run the analytics on that part. This on the other hand won't be as accurate as using the entire set available and might create wrong results.

5) `you can get a pretty good idea by testing yourself, having friends/colleagues test it out, then asking your users about it`: Again, this is completely wrong. Ours is not a homemade project for a dozen users, we're talking about tens of thousands of users each month. Having to ask each user individually for feedback/bug reports is a complete waste of time and is not a viable solution. Moreover, a lot of users are non-technical and won't be able to tell me all the info I need about crashes whereas an automatic error tracking tool can send me the precise stack trace and environment. This way I am able to fix 10 bugs per week instead of 1 bug per month. You probably won't really understand this point if you've never run a large-scale project. This kind of stuff just cannot be done at scale. Do you think Google or Microsoft can contact millions of users for feedback and bug reports? This obviously needs to be automated...

6) `If random users don't want to share, then you shouldn't force it ...... This whole idea that it's okay to forcefully take usage data from people, to try and fine tune software, is honestly quite obnoxious and self entitled`: We don't force anyone to do anything. Our product is provided "as-is". You're free to use it by accepting our terms, otherwise, you are not allowed to use it (as stated in our terms). We use analytics to improve the product. Whether you believe it or not is not our problem. Open source does not mean we are not allowed to run analytics. Open source denotes software for which the original source code is made freely available. You can learn more at https://opensource.org/osd.

7) `As far as networking goes, you can run your client locally and monitor network traffic`: Again, the way I use the app is different from the average user. Moreover, things don't exactly work this way at scale. How 1 person uses the app is not indicative of how other 100k users are using the app. Some people may use certain features in weird and unexpected ways which will lead to unexpected behaviors if not monitored.

8) `The problem is going through a company like Google, and the lack of legal protections to guideline what can be taken`: As I said I am looking for alternatives to google analytics, even though basically 99% of the Minecraft launcher alternatives also use them (official one included probably). MultiMC also uses google analytics btw: https://github.com/MultiMC/MultiMC5/blob/develop/launcher/setupwizard/AnalyticsWizardPage.cpp#L51.
FTB uses its own analytics tool: https://github.com/CreeperHost/modpacklauncher/blob/877d007ef892559f0a7adb8f8dd6407e9144397c/src/main/java/net/creeperhost/creeperlauncher/Analytics.java. ATLauncher uses google analytics: https://github.com/ATLauncher/ATLauncher/blob/ac57f4cdb4b774534a1d4579759fe3ce58ee0f23/src/main/java/com/atlauncher/gui/tabs/settings/LoggingSettingsTab.java#L1-L1. Lunar Client and Badlion are closed source but they also use google analytics.

9) `Not everyone is a programmer, and even the ones that are, likely don't want to go delving into the source of every piece of software`: Your lack of interest is absolutely not our problem. Our code is entirely open source and releases are uploaded directly from GitHub actions, the entire process is completely transparent. Usually, if you're that much into privacy means you can also spend some time analyzing the tools you use. How do you know some software doesn't track you anyway even after disabling tracking? 👁️👁️

10) `The responsible thing to do, is to not subject your users to this. Instead you're prioritizing productivity.`: Sure as hell I am. My main goal is to provide the best possible product for our users. Please find me another software with more than 100k MAU that works completely without any tracking and I will be more than available to contact them and ask for help. 

I suggest you look at how and why analytics are actually used in modern software: https://blog.stormid.com/why-analytics-is-important-for-business/

**Comment by Eskaan** [comment]
I got a really simple solution for you, @MechanosG.
1) Learn JavaScript
2) Learn React
3) Fork the Project
4) Remove all the privacy stuff
5) Build the Projekt.
Not that much expenditure for Someone that much into privacy, right? If this is to complicated for you, take an other launcher.

**Comment by MechanosG** [comment]
Ugh.  I hate that I feel I have to even respond to all that.

@killpowa 
So you don't care what other people do, and don't care if people use GDLauncher.  They can take it or leave it.  Open-source doesn't make any of this against any rules, so it's not your problem.  Alright.  Interesting priorities.  Why are you even working on this if you don't care about your users?  Oh right.. you also said you're doing all of this "for" your users.  But it's their problem, not yours.  Wait what?

Contradictions aside, you keep re-justifying using analytics because "other people do it" and because running your open source software "like a business" is the way to go.  But your sketchy Privacy Policy outlines that it can be used for more than simple analytics, and that partners will take the data.  It's the only reason I even made this issue, because your Privacy Policy is basically saying "You agree to all of these possibilities", and there's no opt out (yet).

And you know what?  Fine.  I didn't come here to argue.  I will admit that maybe I should be a "little" more open minded to analytics.  I never once accused GDLauncher of taking any connectable data.  But when I see a sketchy privacy policy mentioning partners, retaining data, and Google is involved?  Yeah, I'm going to start questioning things, and looking for the opt out.

You want me to pick out high daily/monthly used software without analytics?  I could pick out 100 video games if you like?  It's still software, and they don't use analytics for every game mechanism to see how people are using it, yet their software is still highly successful.  Build your game, test your game, let people play the game, listen to feedback.  Build your app, test your app, let people use the app, listen to feedback.  I'm sure you won't accept that answer, but oldschool approaches still work, and they don't require any trustfall exercises.  https://stackify.com/what-is-sdlc/

Regarding the link talking up analytics, it flat out mentions an example of how data collection has been abused and brought up to the public.  Then it doubles back to how large scale analytics benefits businesses, particularly in being able to better see how profitable various expenditures are.  Then it turns around and acts like this "ill gotten" data should be taken advantage of (in reference to Cambridge/Facebook/etc) because it's commonplace.  Which I hope I don't even need to explain why that hurts that page's credibility.  Profit/Power > Everything else?  No bueno.  I do understand the concept of not having data on a specific venture, resulting in having to take a chance and/or requiring more effort/resources.  But I also understand that people are willing to trample on other's liberties just to obtain that information, and then others still, see this already collected data as an opportunity.  So it's not as cut and dry as you make it sound, despite how well analytics works.

As far as MultiMC goes, MultiMC tells exactly what data is taken, and then lets you turn it off without losing any features.  That's transparency, with an opt out.  In comparison, expecting people to look up the source code to see what does what, after a sketchy privacy policy hints at what "could" be taken, is not transparency.  Your average user will not be able to do that, and I think you know that.  Actually, if you followed in MultiMC's footsteps, told exactly what data you take, then provided said opt out, that would be really cool of you.

I'm not even going to respond to your privacy pokes, as Surveillance Capitalism affects everyone that uses any kind of computer, not just programmers.  Although I do find it interesting that you're implying you might lie about an opt out.  👁️👁️

@Code-Ac 
1. I already use it
2. Have never needed it, but it's interesting now that I'm looking at it.
3. No thanks.
4. Because that's easy, right?  Swap API address, learn how official API works, make sure the rest of the code can interface with the official API properly (probably doesn't anymore), patch out existing features that rely on the custom API so they don't error out.  Other stuff.
5. Didn't take any time at all.

Imagine responding to an "opt out" suggestion in a Github issue for software you work on, where the user has already had a discussion that devolved into an argument about privacy and analytics, so said user says he's going to temporarily go use another launcher.  And you respond anyway, telling the poster to go make the changes themselves, in 5 (_probably condescending_) steps, because if they really care they'd put in the work, and otherwise go use a different launcher.  lmao

I like your skunk.

**Comment by blarfoon** [comment]
Since I'll be referring to our privacy policy a lot, I'll denote it as "PP" from now on.
Bruh, I don't think you have even read our PP, to be honest. It's clearly stated everything we collect and how we use it.
I am wasting so much time responding here but I will use this issue as a reference for all future PP issues.

If you're into privacy stuff either use our opt-out feature with some features being disabled (coming soon), modify it or use another software. Disabling features in the opt-out is not my choice but rather a technical limitation. Some services we provide and will provide require tracking or collecting some kind of information to a certain extent in order to work (payment processing, hosting data, and so on...)

We have a super clear PP that explains EVERYTHING we do with the data. We don't sell it, we don't harvest it, we don't abuse it. Just read the PP.

I feel this is extremely unnecessary because it's already written in the PP but we do not "give" any data to our partners. It's clearly written that we will not share any personally identifiable information with third parties and will not share any information with unaffiliated third parties. It's also written that "Service Providers" are not authorized to use or disclose your information except as necessary to perform services on our behalf or comply with legal requirements.

That means we MIGHT share some generic analytics with our partners in order to be able to work together but none of the info we share is personally identifiable information.

Our PP covers a lot more cases than we currently need but I don't really like changing it 1000 times so that covers all our current and future needs.

As I said, we'll be moving away from google analytics when I have time to do that and we do not share any data with our partners. If those were your only concerns you can relax. Our privacy policy is a bit extended for our current needs but is not sketchy at all, it's actually very precise on what we do and do not do.

`How do you know some software doesn't track you anyway even after disabling tracking? 👁️👁️` was clearly not referring to me but to software in general, since you said you're not interested in reading source codes.

**Comment by Eskaan** [comment]
> That means we MIGHT share some generic analytics with our partners in order to be able to work together but none of the info we share is personally identifiable information.

As far as I know He is referring to things like User count. The partners will want that to see if the partnership is still worth it.

**Comment by MechanosG** [comment]
Alright, lets skim through a bit.
```
When you open the Website or use the Application, our servers automatically record information that your browser or device sends. This data may include information such as your device’s IP address and location, browser and device name and version, operating system type and version, language preferences, the webpage you were visiting before you came to the Services, pages of the Services that you visit, the time spent on those pages, the information you search for on the Services, access times and dates, and other statistics.

Information collected automatically is used only to identify potential cases of abuse and establish statistical information regarding the usage and traffic of the Services. This statistical information is not otherwise aggregated in such a way that would identify any particular User of the system.
```
IP, location, browser, device name, OS, etc.  There's a good start.  Only used for abuse and statistics.  Which means..  anything really.
```
You can access and use the Services without telling us who you are or revealing any information by which someone could identify you as a specific, identifiable individual. If, however, you wish to use some of the features offered on the Services, you may be asked to provide certain Personal Information (for example, your name and e-mail address).

We receive and store any information you knowingly provide to us when you create an account, publish content, make a purchase, or fill any online forms on the Services. When required, this information may include the following:
```
Etc etc.  So basically, if a feature is offered and personal information is required to use it, you may be asked to provide it.  However, it then says it's automatically stored when you do anything.  So Username, Email, Password.

```
Some of the information we collect is directly from you via the Services. However, we may also collect Personal Information about you from other sources such as public databases, social media platforms, third-party data providers, and our joint marketing partners. Personal Information we collect from other sources may include demographic information, such as age and gender, device information, such as IP addresses, location, such as city and state, and online behavioral data, such as information about your use of social media websites, page view information and search results and links.
```
I mean, it's right there.  I'm copy pasting this directly out of GDLauncher.

```
We will retain and use your Personal Information for the period necessary to comply with our legal obligations, as long as your user account remains active, to enforce our agreements, resolve disputes, and unless a longer retention period is required or permitted by law.

We may use any aggregated data derived from or incorporating your Personal Information after you update or delete it, but not in a manner that would identify you personally. Once the retention period expires, Personal Information shall be deleted. Therefore, the right to access, the right to erasure, the right to rectification, and the right to data portability cannot be enforced after the expiration of the retention period.
```
Data will be kept, as long as it's legally classified as unidentifiable.  Also mentioned elsewhere.

```
How do you know some software doesn't track you anyway even after disabling tracking? 👁️👁️ was clearly not referring to me but to software in general, since you said you're not interested in reading source codes.
```
Obviously you weren't talking about yourself, even though you are one of the developers of an app you spoke of.  Which is why I found it appropriate to return the favor.

**Comment by MechanosG** [comment]
Anyway, look.  I really don't want to argue this anymore.  It is what it is.  I'm not trying to pick a fight, and I'm not suggesting you're actually intentionally collecting any of that.  That's just what's in the PP.  I am taking your suggestion and relaxing lol.  Anyone interested in this subject, can go see the PP themselves.  Have a good evening.
