### ISSUE TITLE
Forge issues

### ISSUE THREAD

**Issue by theodorejones** [gorilla-devs/GDLauncher#1131]
Forge is currently refusing to download for any version. It'll download the game files, start downloading Forge, and get stuck on 0%

**Comment by miguelallopes** [comment]
Good night, the temporary solution for your problem is switching the release channel from stable to beta

![image](https://user-images.githubusercontent.com/43732860/138611295-9f04b2d9-706d-4d49-a260-124dbf6945fc.png)

Then restart the launcher, update it to the latest beta version (green button which will appear on top of screen) and you are ready to go

**Comment by Eskaan** [comment]
Thanks @PWRScript for telling him ❤️

**Comment by Eskaan** [comment]
Duplicate of #1086
