### ISSUE TITLE
Instance is killed during launch

### ISSUE THREAD

**Issue by guitoo** [gorilla-devs/GDLauncher#135]
GDLauncher kills the instance during the launch.

I tried to pull a quick pack with a few mods, but GDLauncher hit me with this error during launch:
`Cannot start this instance. Error: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded`

OS:Gentoo Linux

**Comment by blarfoon** [comment]
This is caused by the nodejs child process creation. It looks like `exec` saves the output in the buffer and releases it when the game is closed. The buffer has a default size of 200kb, when it exceeds that limit, it ends the process.
The solution I found so far is using the `spawn` function. That way the output is treated as a stream and it can't overflow. The only drawback is performance-wise since it console logs every line in real time.
Starting enigmatica 2 gives this results on my pc (Ryzen 7 2700x on NMVe):

- Startup time with console logs: 5 min 30 sec
- Startup time without console logs: 5 min 10 sec

I think it's not a big deal but maybe we should set an option for console logging the output, related to #129. What do you guys think?
