### ISSUE TITLE
Remove Colour Picker 

### ISSUE THREAD

**Issue by GeorgeWL** [gorilla-devs/GDLauncher#137]
The only apps that need that are apps that someone is going to be staring at for hours, stuff like Code Editors and Word Processors.

Anything else, it's just creating more problems than it's worth.

You should either have no theme choices, or only light and dark.

_Sent from my Pixel 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by blarfoon** [comment]
Even though I may agree with you about your first sentence, I don't with the latter.
One of the main goals of the launcher is to have a clean yet powerful interface with strong customizability.

Themes are not essential but give users that option to personalize the their experience.

 It's true that people don't stare at it 24/7 but in the future, it'll have a lot of features to debug the game and help mod and packs developers doing their work.

 I think removing it completely it's an error but I can agree on removing it from the home screen.

**Comment by blarfoon** [comment]
I read your other issue too. I'll think about it, maybe asking users too

**Comment by blarfoon** [comment]
After asking the community, we decided not to remove it for the following reasons:

- Users like it.
- Users want more customizability, not less.
- Since users can change colors, it's up to them to keep consistency with the news or other fixed components.
- It is true that removing it would help to remember the branding but I don't think it's a big deal in this case.
- The main goal of the launcher was to differentiate from the other launchers (why would it exist otherwise?). No other launcher supports theme customization (afaik)

Aside from this, I've read your other issue too and I do agree with most of your suggestions.

I'm closing this issue but feel free to re-open it for further discussions

**Comment by GeorgeWL** [comment]
My thought is this: some features are seldom seen because they're not worth the effort to install
