### ISSUE TITLE
Auto Java Installer

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [gorilla-devs/GDLauncher#145]
Automatically install java 8 without the need of having it

This can relate to this comment i posted https://github.com/gorilla-devs/GDLauncher/issues/110#issuecomment-452420690

**Comment by hron84** [comment]
This could be hard since Oracle does not allow to download Java Runtime Environment without accepting their license on the download page. Any attempts to bypass this requirement maybe against their licensing (I'm not sure about what the license exactly says but I'm pretty sure they made this step). 
So currently the only legal way to install Java is doing manually. Twitch client partially bypasses it by downloading Minecraft Runtime that is developed by MS / Mojang (and moving responsibility to them, but this has a quite old JRE) or requiring you to have Java installed. 

Sorry, in this case, I have to downvote. I'd be glad if Oracle could be more open in this question but until this happens, I'd rather vote to prevent this project to be abandoned by licensing sharks.

**Comment by CrankySupertoonArchive** [comment]
But java isn’t made by Oracle they just publish a binary with business features. The real java is OpenJDK and a fork can be downloaded here 
https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html

**Comment by CrankySupertoonArchive** [comment]
Not to mention that the old gdlauncher has it

**Comment by hron84** [comment]
And all mods in all modded Minecraft version on all platform is tested against OpenJDK? I bet not. Even more, I have knowledge about some mods has problems with specific Java versions and also OpenJDK has bugs on non-Windows platforms that causes random crashes in Minecraft. I think if someone pops up with a launcher that is multiplatform (and since new GDLauncher based on Electron, it totally is), that launcher should offer the best runtime for all supported platforms. 

AFAIK Twitch Desktop supports Oracle JRE and I'm pretty sure it's not a coincidence. Oracle JRE contains not jus business features but a bunch of other patches across all the runtime. If someone tried to support any Java-based application (and I did it), should already know it.

Don't get me wrong, I would be glad if OpenJDK could work for GDLauncher. I'm not paid by Oracle, nor wear Oracle t-shirt all day. I'm just worrying because GDLauncher has so many possibilities that could bring a better world for non-Windows gamers and I'd like to ensure this opinion will be considered.

**Comment by blarfoon** [comment]
I feel like right now this is not something I want to add. I think users prefer to use their version of java and it's a waste of disk space to download another java runtime.

From what I know openJDK creates more problems than it solves with Minecraft so I would exclude it as a solution.

Oracle's jre could be implemented but it creates some new problems. There is no portable version of their jre, I would need to download it from somwhere else.

Imho this is something that could be useful to a bunch of people but not something to spent too much time on at the moment

**Comment by hron84** [comment]
I absolute agree on that. However, please consider testing your launcher on non-windows platforms too (especially because on Linux Java Runtimes can come from different places) and allow users to add multiple JREs to the launcher and change global ones for an instance just like how MultiMC does. I can imagine some really old packs (MC 1.5.2, 1.2.5) cannot run with latest JRE.

**Comment by CrankySupertoonArchive** [comment]
They coded it so it can
