### ISSUE TITLE
Sound doesn't work work for versions 1.7.3 (non-beta) and below.

### ISSUE THREAD

**Issue by Zer0Lyfe** [gorilla-devs/GDLauncher#146]
**Describe the bug**
It seems that versions 1.7.2 and every version below that do not have sound from Minecraft at least. I presume it was moving of libraries or something of the sort as i download like 10 different version below 1.7.3 (not beta) and has had no volume to the Minecraft menu such as single player or the multiplayer button. 

**To Reproduce**
Install a Vanilla Instance of any choice of 1.7.2(not beta) or below.
click on the menu buttons such as singleplayer and hear nothing from the buttons or menu music.

Duckabush has found out that it works on other minecraft launchers such as twitch and i have confirmed it works for multimc but not GDLaunchers

**Expected behavior**
sound to work for minecraft menu and the menu music to play.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chromium and firefox]
 - Version [version 71 for Chromium and 64 for Firefox]

**Comment by CrankySupertoonArchive** [comment]
This isnt a bug, Mojang removed the audio files from being downloaded in packs before 1.7.10. I would just close it because there isnt much to do, unless you want to auto apply a resource pack with the sounds. 

https://bugs.mojang.com/browse/MCL-6280

This describes near the bottom they ripped native launcher support and shortly after ripped jar launcher support.

If anything the developers of those 2 launchers hacked them back in using ASM or something

**Comment by blarfoon** [comment]
After some digging, I managed to make sounds work down to 1.6.1. Every version below that does not depend on GDLauncher

**Comment by Zer0Lyfe** [comment]
ill just close it then. edit ill reopen it for now until it is "fixed" as said above.
