### ISSUE TITLE
Update mod packs without needing to make a new instance

### ISSUE THREAD

**Issue by MarioAndWeegee3** [gorilla-devs/GDLauncher#173]
I would like to be able to update an instance to a new mod pack version without needing to create a new instance and copy over my data.

**Comment by Dimentive** [comment]
You don’t have to do that. Just install the latest version of the mod in the mod manager in your instance, which you can do even if the mod is already installed, and then, remove the old version by searching for the file in your list of mods, also in the mod manager.

Of course, it’d be more convenient if you were able to simply update mods directly from the mod manager, but you don’t have to create a new instance and copy your data over.

Also, this is already being worked on. @killpowa said that it would likely arrive in the 0.13.00 update of the launcher. Here’s to hoping it’s soon. 😄

**Comment by fuzzyweapon** [comment]
Even though this is already being worked on, re what Dimentive said.  It's not enough to be able to just update to latest of each mod.  Many time, as a modpack author, I want to stick to versions that support Optifine's latest for my players and this means not taking latest of the mods.  I do all of that testing **for** them, so as a modpack author, I really would like to pass that benefit on, otherwise there's not much motivation to use this launcher over vanilla.

**Comment by Dimentive** [comment]
Why was this closed? Was the feature added?

**Comment by TOLoneWolf** [comment]
right click instance > "manage" > "modpack versions" tab > select version from drop down on top > "update modpack " bottom of window.
