### ISSUE TITLE
Change indication for starting an instance

### ISSUE THREAD

**Issue by mount2010** [gorilla-devs/GDLauncher#279]
**Is your feature request related to a problem? Please describe.**
My friends and I have been confused with how to start an instance. I believe many other new users would find this confusing, too. This is caused by improper indication about whether an instance is running, as it takes a while for the Minecraft window to show up. This is made worse by the fact that clicking more than twice will force-quit the instance.

**Describe the solution you'd like**
At the very least, double clicking to force quit an instance should be disabled. It is the instinct of a user when something does not work immediately to spam the option until it works. There could also be an indication that the instance is starting up, for example a toast saying "Starting \<instance name\>". Players can still force quit an instance by right clicking and selecting "Force Quit" (or something like that).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by furtabs** [comment]
Doesn’t a play icon appear in the corner.

**Comment by mount2010** [comment]
It does. But this indication is confusing when nothing happens immediately afterwards (it takes about 20 seconds for the Minecraft window to show up). The instinct then ("is it not working?") is to click the instance again, forcefully exiting it. When the indication "forcefully exited by user" shows up, it is even more confusing, as the user did not expect "double click" to mean "force exit without confirmation".

**Comment by kreezxil** [comment]
I agree. This confused me too. Sadly, like I do with some apps with poor
gui designs, but the app itself having merit I reconditioned myself to not
be to quick on the draw.

It should be noted Edwin, that Twitch is the same way. You click on play
and there is nothing for 30 seconds to a minute to indicate that it's
pre-initializing the pack you chose, not even a play button as the GD devs
have been so kind as to provide. Then you get the Mojang launcher, which
you then have to hit play on, and then there's another 30 seconds to a
minute of absolute nothing before another window appears.

Well, hmmm, after describing it, it would appear that Twitch is even worse
in this one regard. Because with GDLauncher, you double click to start the
instance, a play button appears, you wait, the game itself actually starts
and not just another screen you have to hit play on.

I would recommend to stop double clicking the icons tho, instead right
click them and choose the options.

**Comment by kreezxil** [comment]
Just thought of something, if the instance isn't running, maybe a square stop icon should appear where the play icon would be if it is running.

**Comment by furtabs** [comment]
Nah every pack would have a square then
