### ISSUE TITLE
Doesnt Launch any Modpacks

### ISSUE THREAD

**Issue by ghost** [gorilla-devs/GDLauncher#374]
**Describe the bug**
I cant seem to launch any modpacks whatsoever. When I click launch a play symbol appears for a fraction of a second, then disappears, and nothing happens at all

**To Reproduce**
1. Download and Install any Modpack
2. Click on "Launch"
3. Nothing happens

**Expected behavior**
Either the modpack or the minecraft launcher should start.

**Possible solutions**
Maybe a reinstall, but I've already tried that. I don't know what I'm doing wrong as Ive never used the gd launcher working

**Operating System:**
 - OS: Windows 10 64
 - Version 10 uppdate 1907

I dont really know what else information would be helpful as I dont have any crash logs, so just tell me what would help.

**Comment by ghost** [comment]
Ok I found the Crash Report https://pastebin.pl/view/6d1a4b16

**Comment by TOLoneWolf** [comment]
That past link 404s (not found).

But I have a pretty good idea oh what the issue is.
Following this should get you going:
https://github.com/gorilla-devs/GDLauncher/wiki/java-64-bit-installers
Might have to remove and re-add the modpack after.
Vanilla should work with out remove and re-adding.

If it gives you any more trouble after that.
Copy of the log as shown in the link:
https://github.com/gorilla-devs/GDLauncher/wiki/Console-and-Log

**Comment by Ptikev** [comment]
It did the same thing for me after a fresh install of the pack and e4, i just restarted my pc and then the instance launched.
