### ISSUE TITLE
[Feature] Select Java version per instance

### ISSUE THREAD

**Issue by tloskpd** [gorilla-devs/GDLauncher#400]
Requesting the ability to change java version per instance like RAM and arguments overrides.  

I play packs from different minecraft versions and would like to not have to change the global path to point to java 11/8 each time

**Comment by furtabs** [comment]
What version of minecraft absolutely Requires Java 11. Pretty sure latest forge still works with java 8

**Comment by tloskpd** [comment]
None but the option to run java 11 on newer mod packs would be nice while not having to adjust global parameters to switch to java 8 for older ines

**Comment by TOLoneWolf** [comment]
A use case would be forge versions that work with Java OpenJ9 to improve performance but will not work with others allowing the main global default to be used.

**Comment by kreezxil** [comment]
this is interesting

**Comment by ghost** [comment]
If you want a use case how about the fact that some mods such as DynamicSurroundings [now require Java 9](https://github.com/OreCruncher/DynamicSurroundings/issues/659).

**Comment by OreCruncher** [comment]
To be clear the packaging of Forge 36 changed to include a Nashorn engine so that Forge can run on newer versions of Java.  It is breaking because that Nashorn package is built with Java 15, and when it loads on Java 8 an exception is thrown.  Forge team is aware.  I am also making a hack to avoid this situation, but other mods that use JavaScript may trip over this.

(I would recommend per instance setting of Java as well.  It would help the transition of players that want to use newer Java where possible but still maintain the ability to play older packs.)

**Comment by Renari** [comment]
Java 14 also includes GC improvements that help with MC stuttering.

**Comment by PseudoResonance** [comment]
This is a lot more important now with newer versions requiring Java 16, but older versions not running at all on Java 16. It's definitely frustrating to have to switch Java install locations each time I want to start up a different modpack.

**Comment by RemagOfficial** [comment]
> This is a lot more important now with newer versions requiring Java 16, but older versions not running at all on Java 16. It's definitely frustrating to have to switch Java install locations each time I want to start up a different modpack.

this has been added already

**Comment by PseudoResonance** [comment]
I see, thank you. For some reason my client was stuck on 1.0.9 and thought it was the latest version. This issue should probably be closed too to prevent confusion.
