### ISSUE TITLE
Add 1440p resolution to game resolution preset list

### ISSUE THREAD

**Issue by TheDeviantCrafter** [gorilla-devs/GDLauncher#508]
In GDLauncher's global settings under Java, there's a section to set the resolution of the game. Next to that setting is a list of common presets like 720p or 1080p. I would like 1440p, 2k and 4k to be added to that list since they're common settings.

**Comment by fabm3n** [comment]
They are implemented: https://github.com/gorilla-devs/GDLauncher/blob/master/src/app/desktop/utils/constants.js#L16

They are only displayed if your display has this size: https://github.com/gorilla-devs/GDLauncher/blob/master/src/common/modals/Settings/components/Java.js#L261

I can't test if it's working because i only have 1920x1080.
