### ISSUE TITLE
Provide a config option to use JAVA_HOME for the desired Java version.

### ISSUE THREAD

**Issue by LindaJuffermans** [gorilla-devs/GDLauncher#528]
**Is your feature request related to a problem? Please describe.**
In my opinion, Java is part of the system and should not be part of the launcher. I take good care to keep my Java up to date, the Java updater nicely notifies me when the new version can be installed. If other applications keep their own copy it's a) inefficient and b) unclear when they get updated. Multiple installations of the same Java (e.g. GD launcher, MultiMC, Twitch) should not be a thing.

**Describe the solution you'd like**
I would like GD Launcher to use my JAVA_HOME when it's looking for the JRE. I understand that for some less technical players this may not the best option but if you offer it as a configuration option, people can choose it if they understand the impact.

**Describe alternatives you've considered**
I have currently manually set the Java path in the GD Launcher configuration but that means changing the configuration every time Java is updated; the same path is already available through JAVA_HOME.

**Additional context**
--

**Comment by furtabs** [comment]
Since JAVA_HOME is an environmental Variable you might be able to just feed it JAVA_HOME in the path box. example is on Arch i just type java.

**Comment by Eskaan** [comment]
If the above option does not work, I would recommend just selecting the manual setup and putting your JRE path in there. That will definetly work and will do what you want, I guess. Otherwise, the JAVA_HOME variable does not work in 50% of the cases because its either not set or points to an Java version that is not Java 8. In addition to that, we need Java 16 for the newest versions of Minecraft (1.17+).I hope this is okay for you, but this will not be done. Anyways, this was a good idea. 🙂
