### ISSUE TITLE
Impossible to download modpacks with long/otherwise invalid names from Curseforge

### ISSUE THREAD

**Issue by Dthen** [gorilla-devs/GDLauncher#552]
**Describe the bug**
If you try to download a modpack from the "Browse Modpacks" interface and GDLauncher doesn't like its name, a text box will appear with the name of the modpack, alongside an error saying "Instance name is not valid or is too long. Please try another one". The text box is not editable and there does not appear to be any way to change the instance name GDLauncher should use.

**To Reproduce**
1. Open GDLauncher
2. Click the plus on the bottom left of the UI.
3. Click "Browse Modpacks"
4. Search for "Dthen" using the search box at the top right of the "Add New Instance" interface
5. Click install on the first and only result, "Delicate Dthen's Deceptive Download"

**Expected behavior**
Modpack installs

**Possible solutions**
If the restrictions on names cannot be changed, I would make it possible rename the modpack by editing the text box which appears on the screen which displays the error message (shown in attached screenshot).

**Screenshots**
[GDLauncher_qBAI9Ayd1W](https://user-images.githubusercontent.com/65791582/86177347-5f451f80-bb1e-11ea-9d13-16052426dc6b.png)

**Operating System:**
 - OS: Windows 10 Professional

**Comment by ChaseIngebritson** [comment]
So I think this may be a case of a misleading textbox rather than an actual bug. The text in the box isn't actually highlight-able nor can you modify text in the middle of the name, but you can start typing from the beginning of the box to overwrite what was in there originally.

![2020-06-30 17_29_48-GDLauncher](https://user-images.githubusercontent.com/11217065/86183458-a2d86300-baf7-11ea-9fd0-801d59c55fae.png)

The textbox definitely should be modified to act as expected though. This would probably include:
- Allowing modification of text in the middle of the name
- Allowing highlighting of sections of the name
- Not removing the existing name when the user begins to type
- Letting the user know how many characters can be entered

**Comment by Dthen** [comment]
Oh, aye, right you are, I can indeed change it so long as I place the cursor at the beginning of the text box. Thank you, I would never have worked that out by myself. I think not being able to delete the text in the box really threw me off.

Definitely an issue, just not the one I described. Hah.
