### ISSUE TITLE
Optifine standalone

### ISSUE THREAD

**Issue by ghost** [gorilla-devs/GDLauncher#571]
Hello, i am making a feature request for a optifine mode (forge, fabric vanilla, OPTIFINE) or at least it showing up in the mods category.

**Comment by ChaseIngebritson** [comment]
From what I understand, currently this is not a possibility due to issues with Optifine's copyright policy and their lack of an API.

> The mod OptiFine is Copyright © 2013 by sp614x and the intellectual property of the author. It may be not be reproduced under any circumstances except for personal, private use as long as it remains in its unaltered, unedited form. **It may not be placed on any web site or otherwise distributed publicly without advance written permission.** Use of this mod on any other website or as a part of any public display is strictly prohibited and a violation of copyright.

From their [minecraftforum.net post](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1272953-optifine-hd-fps-boost-dynamic-lights-shaders-and), bolding done by me.

So until GDLauncher is granted express written permission to host the mod, the mod developer sets up an API to provide the mod via their website, or they change their policy, this probably won't be doable.
