### ISSUE TITLE
Provide more information when instance can not be launched

### ISSUE THREAD

**Issue by rdellison** [gorilla-devs/GDLauncher#608]
I updated a number of mods in a private instance, and afterward "OOPSIE WOOPSIE!! A creeper blew this instance up!" with error log "Exception in thread 'Thread-17'"

I would like to have a an easy way to pull up the crash log - the "exception in thread" error log is not helpful at all.
It would be great to have a list of changes to the mods in the pack since the last version that was able to launch.

I browsed through my app data folder to find the logs subfolder of the instance that crashed.  (not clear from that which mod was responsible - something to do with 'ItemColors').  Looking through the mods folder I see the 17 mods that were updated today but not clear which previous version I was running of each of them.

**Comment by Eskaan** [comment]
We cant provide more information than Java wants to give to us. Analysing the logs is nearly impossible because we cant predict errors.
If you want really detailed information, who probably has nothing to do whit the crash itself, look into the console or open the instance folder and open the `latest.log` file.
