### ISSUE TITLE
Updating imported instances or "private" modpacks

### ISSUE THREAD

**Issue by Jensig** [gorilla-devs/GDLauncher#677]
**Is your feature request related to a problem? Please describe.**
I want the behavior of a curseforge hosted modpack where the updates is installed directly on the instance instead of a new instance, so that I can send updated zip's on i.e. Discord for the people on my server. The issue with the current approach is that local files for i.e. configuration and maps is lost in the update process because of the new Issue.

**Describe the solution you'd like**
One solution for this wold be to create "private" modpacks that can be updated with a new zip file. The zip file wont have to be hosted on i.e. curseforge because it could just be sent on Discord or outer ways. 

**Describe alternatives you've considered**
At the moment I'm using curseforge to send updates to the users on my server but it's a small server and uploading that to  curseforge is more complex then I'd like to.

Thanks!
Jensig

**Comment by thaimichael** [comment]
This is similar to https://github.com/gorilla-devs/GDLauncher/issues/590

My suggestion.

Short version:
Allow a local repository for private offline modpack zip files in the instance folder when created locally.

Long-winded version:
My idea on this is when a private pack installs it copies the modpack zip file to a subdirectory in the instance.  
This subdirectory would be the location for subsequent update zip files imported to the same subdirectory either automatically or manually.  
This would then allow you to choose which version to use just with the offline directory being the repository for the versions rather than the normal online curseforge repository.  
This type of setup would be very useful to support the development and testing of modpacks still in private testing.

**Comment by Eskaan** [comment]
Duplicate of #590
