### ISSUE TITLE
Todos / Ideas

### ISSUE THREAD

**Issue by blarfoon** [gorilla-devs/GDLauncher#70]
This will be the complete official list of **ideas/ todos**. 
If you want to add something, comment below and after discussing it, I will add it here.

* Launcher
   *  [x] Implement an autoupdater
   *  [x] Add loading indicator for skip login
   *  [x] Fix the blank space in the news component (the line next to the buttons)
   *  [x] Make the system navbar a little higher

* Instances
   *  [x] Add vanilla download
   *  [x] Add forge download
   *  [x] Add curse modpack download

* Switch from AntDesign components to custom
   *  [x] Modals
   *  [x] Menus
   *  [ ] Buttons
   *  [ ] Inputs
   *  [ ] Popover
   *  [ ] Select
   *  [ ] Dropdown
   *  [ ] Steps
   *  [ ] Checkboxs
   *  [ ] Mention
   *  [ ] Radio
   *  [ ] Slider
   *  [ ] Switch
   *  [ ] Transfer
   *  [ ] Upload
   *  [ ] Avatar
   *  [ ] Badge
   *  [ ] Tooltips
   *  [ ] Tags
   *  [ ] Three
   *  [ ] Alert
   *  [ ] Message
   *  [ ] Notification
   *  [ ] Progress

For reference see [here](https://ant.design/docs/react/introduce)

* APIs
   *  [ ] Evaluate possible security issues in making them open source
* Website
   *  [ ] Make a new website (yay)

**Comment by camatthew** [comment]
Add multimc modpack support

**Comment by Blackcatmaxy** [comment]
changing file path would be really nice

**Comment by blarfoon** [comment]
What do you mean by file path?

**Comment by Blackcatmaxy** [comment]
the folder where the instances are, so if you have another drive you could set it to use that drive instead

**Comment by erikLundstedt** [comment]
adding a more easy to find minecraft debug output would be good

**Comment by sscards55** [comment]
I have a couple ideas:
- Curse project detection/Mod name detection.
Depending on how you want to go about it you could read the mcmod.info file in the jar file to get the mod name, this would be nice because some mods have discrepancies between the mod name and the jar file name.

- An update button for mods.
This one ties into the previous one, having an update button for mods that have an update available would be nice. Also if possible, removing the old version of the mod when updating.

- Better support for the backwards/forwards button
Right now the way it's implemented if you press the back button in a mod page or the get mod list you go all the way back to the instances tab.

**Comment by bbuchalter** [comment]
It would be nice to be able to add custom mods that aren't on curse. When I'm making my own mods, before I release them to curses, it would be nice to be able to distribute them to my friends easily via gdlauncher.

**Comment by Gotolei** [comment]
An option to disable the Discord rich presence.

**Comment by LordMZTE** [comment]
add a display that shows the download speed when installing packs

**Comment by iconmaster5326** [comment]
Support for Fabric and Rift instances, in addition to Forge, would be nice.

**Comment by mahldcat** [comment]
An option to export a pack as a curse/twitch compatible archive?

Use Case:
1) Install a pack from Twitch
2) Manage the mods doing various CRUD ops to the pack
3) Export the pack

Result:
Instead of having the populated "mods" folder etc, the manifest file is updated/generated.

**Comment by mahldcat** [comment]
An option to export a "server pack" archive?  

(Just some thoughts on how something like this might operate):
0) Keep a running list of mods that should be black listed (e.g. client only mods)...this would need some means to pattern match...e.g. "Optifine*" )

Use case: (What I was having to do manually last night)
1) Installed a fresh instance of FTB Revelations
2) Add nuclearcraft, building gadgets etc to the pack (aka the mods that Direwolf20 used to customize his pack
3) Modify the nuclearcraft config to disable a subset of the oregen (copper, tin etc)
4) Update dank null lib (as well as several others so this thing actually works :D)

5) Click on the export button where I'd be presented with an "export server pack" option

Actions Taken:
1) Generate a local folder that would be first populated with an empty "forge server" template that would provide the necessary sh/bat files to setup a blank forge instance
2) The mods folder in this case would be populated by the current instance's mod folder that don't pattern match against the list of black listed mods
3) The configs/other folders would also be populated by the current instance's folder structure?

**Comment by AzureDoom** [comment]
@mahldcat you can already import and export as a twitch/curseforge pack

**Comment by RovkirHexus** [comment]
Add a filter option to search, and have more search terms narrow the search instead of widen it. Searching "Enigmatica" only shows Enigmatica packs, but searching "Enigmatica 2" shows all Enigmatica packs and all packs with a 2 in the title.

**Comment by AzureDoom** [comment]
That's due to wonderful CurseForge api. It's a pos.

**Comment by kreezxil** [comment]
can't you do some extra overhead tho? maybe have a check box in the general
config for gdl called "perfect search", then if that is checked, you split
the users search phrase into a sequence of words, because they checked that
box, that's your  license to use the users computer like the little !@#$ it
wants to be. So you send the api a search for each term in the list of
words, then use cross aggregation to find "enigmatica 2" as an example.

I'm not a leet programmer, maybe even barely a programmer, but I would
probably try at least that approach instead of throwing the ball repeatedly
to curse which as we all know from throwing the ball to them for 6 years
now, they don't ever receive that ball very well at all.

**Comment by Szum123321** [comment]
Could you add Fabric support?

**Comment by LordMZTE** [comment]
GDL should warn you if you are about to install a fabric mod on a forge instance

**Comment by sscards55** [comment]
LordMZTE, there is no easy way of doing that.

**Comment by LordMZTE** [comment]
> 
> 
> LordMZTE, there is no easy way of doing that.

oh, so the API of curseforge doesnt support getting a mod's version? on fabric mods it says "Fabric" on the website and it would be weird of the api didnt have that capibility, and from there on a simple popup would be enough

**Comment by kreezxil** [comment]
I'm all for doing it the hard way, we need to do it as best we can. I'm
fine if it only detects fabric mods once in a blue moon. Once you implement
it Twitch will add detection too. I want to see you guys compete to make it
better for the players and the pack devs. And if Twitch doesn't do it fast
enough, you know because they are slow AF and part of a huge Juggernaut
called Amazon, that just means you're going to gain market share. This will
lead in turn to crazy @$$ $h!7 like I was proposing in the Patreon chat. We
won't get there tho until we've fractured the landscape with a true Twitch
alternative.

Yes, detect fabric the hard way.

**Comment by LordMZTE** [comment]
ATLauncher Integration Would be great to have and they also have an API

**Comment by CmdrNorthpaw** [comment]
Could you add a feature where on Linux GDLauncher uses the system titlebars instead of its own? It kinda annoys me when apps don't do this because my window controls are usually on the left.

**Comment by bluebear94** [comment]
I'd like support for finding outdated mods in a modpack so I can see which ones need to be updated.

**Comment by AzureDoom** [comment]
@bluebear94 
If you are on the current stable release, it already does that
![image](https://user-images.githubusercontent.com/7415711/77599428-004a8b80-6edb-11ea-82c5-3bd43c94d46f.png)

**Comment by bluebear94** [comment]
Ah, I see. I guess the 'download' icons weren't obvious in their meaning.

Related: installing a newer version of the mod should uninstall the older versions automatically, if that's not already the case.

**Edit:** It seems that clicking on the 'download' icon does that, but I was talking about installing a newer version from the mod page.

**Comment by Masterpolpetta** [comment]
filter modpack with minecraft version

**Comment by ibrokemypie** [comment]
Are multimc and gdlauncher instances compatible? it would be nice to have a way to import existing multimc instances into gdlauncher

**Comment by bluebear94** [comment]
Ability to export a Fabric instance as a Twitch pack using JumpLoader. Right now, it somehow assumes that the Twitch launcher somehow supports Fabric packs.

**Comment by RemagOfficial** [comment]
> Ability to export a Fabric instance as a Twitch pack using JumpLoader. Right now, it somehow assumes that the Twitch launcher somehow supports Fabric packs.

You can't export fabric packs without it being a forge instance with jumploader

**Comment by bluebear94** [comment]
Well, the launcher actually doesn't prevent you from exporting a Fabric instance. It would be useful, though, if such an output were transformed into a Forge pack with Jumploader internally (and vice versa – importing a pack with Jumploader should create a Fabric instance).

**Comment by kreezxil** [comment]
is this no longer worthy of being pinned?

**Comment by Toadby** [comment]
Would love to be able to disable the upper right menu icon on Mac :)

**Comment by blarfoon** [comment]
I always read @kreezxil

**Comment by blarfoon** [comment]
but yeah this is so old let's close it
