### ISSUE TITLE
Login System 

### ISSUE THREAD

**Issue by NovaPlayzGames** [gorilla-devs/GDLauncher#71]
is it like a web server and will that be open source to or will the server  source be lockdown and only the launcher can be accessed i would love to see the login proxy source code it would be cool

**Comment by blarfoon** [comment]
Hello, thank you for reaching out. The login proxy is actually an AWS lambda function written in nodejs. All the APIs of the launcher will be written in both nodejs or go. I would be more than happy to share all the APIs and keep them open source. In order to do that though, I need to carefully evaluate every potential security issue since those APIs will be used to store and access users data (we do not store any sensitive information though).

**Comment by NovaPlayzGames** [comment]
i would love to have a copy of the cloud source because i want to make a modified version of gd for a custom client that i am making and it would be cool it is going to have a messaging system and a friend sys like gd and i would love to use the api for that

**Comment by NovaPlayzGames** [comment]
also im having problems compiling the new source i just dont think it likes my install of npm im gonna reinstall nodejs then i will get back to you on that

**Comment by NovaPlayzGames** [comment]
now it is finally working yes it was my node js i had 7 lol

**Comment by blarfoon** [comment]
After evaluating the situation, I ended up deciding not to share the code of the APIs. The motivations for this decision are:

- The APIs (which include the auth proxy) are way too critical under a security point of view to be shared
- The infrastructure of the APIs is really complex. It is mostly based on AWS and uses a lot of different AWS services (DynamoBD, Lambdas, S3...). It would be really complicated to replicate without a CloudFormation script.

Maybe in the future a custom version of the APIs could be developed and shared but it's not a priority right now
