### ISSUE TITLE
Disappearing instance

### ISSUE THREAD

**Issue by Hoff2567** [gorilla-devs/GDLauncher#715]
Instance I had installed could no longer be recognized by the launcher despite the folder still being there.

As for exactly how it occurred I can't specifically say as it happened when I last had minecraft open and my PSU died with the game on and upon getting a new PSU installed and running the launcher it failed to recognize that particularly installed instance anymore even though it had no issue with others.

Attempting to reinstall the pack instance then copy over the data from the original instance to see if the data within that itself is corrupted.

Windows 10 and pack was MC Eternal, latest version.

**Comment by Hoff2567** [comment]
After attempting said fix the instance disappeared again so the files themselves do seem to be corrupted but is there anything specific I should be looking for to remove/change/etc to fix them? I have quite a few modifications that would be unfortunate to lose/re-do.

**Comment by Hoff2567** [comment]
So turns out the entire config file became 'null' after the crash. Not sure if anything can be found from it but can upload if needed.

**Comment by blarfoon** [comment]
Thanks for the report. This is a known issue but I couldn’t figure out why it’s happening. It seems related to the pc crashing and your case confirms this assumption. If you could provide more context about what exactly you were doing when the crash happened it may help. Was the launcher still open while playing the game and it crashed? For how long have you been playing that instance when it crashed? How many mods do you have? Could you provide me your launcher logs on discord?

**Comment by Hoff2567** [comment]
Absolutely happy to provide anything to help. Brice#3985 on discord.

At the time of the crash the game should have just been running, paused, as I was away from the pc doing something else. The game had probably been open for ~4 hours or about that area and the launcher was open as well, yes. The instance had around 6 or 7 days on the selection screen iirc. It has just under 300 mods in the 290 range.

**Comment by takashi1kun** [comment]
I think this behaviour could be avoided if instances where saved in a different directory than the main data of the application. then creating a registry key on windows or a file on /var for Linux or whatever is on mac is created and this registry key or file only contains a string pointing to the directory of the instances, so when GDLauncher is started, it read this key/file and loads the instances from the directory, then it loads its own configuration and data, this way, even if the main configuration is corrupted, it always can at least load the instance data, plus it would make it more painless for updates, since it would have this key pointing to the instances even if it cannot detect its own installation directory.

I had a similar problem after i ran it from source, then return to the installed version, the built from source one was capable of detecting the installation of the installed version, but after running the built from source one, the installed one was not able to load the config nor the instances and i had to do some manual fixes to get it to load them, if the instances were treated the way i proposed this problem would be avoided since even if one nukes the other's configuration, both would respect the existence of this file/key pointing to the instances and both would just load the instances from that directory.

**Comment by blarfoon** [comment]
Hopefully fixed by https://github.com/gorilla-devs/GDLauncher/commit/c5c3c6ad4c263bb19f74e332598d444be3ff6c04
