### ISSUE TITLE
Can't login using Microsoft account

### ISSUE THREAD

**Issue by LapizGaming7751** [gorilla-devs/GDLauncher#788]
**Describe the bug**
Tried to use the Microsoft account to login to GDLauncher. Does not work

**To Reproduce**
1. Basically loginwhile using your microsoft password

**Expected behavior**
Login success

**Possible solutions**
No idea

**Screenshots**
![image](https://user-images.githubusercontent.com/56995425/108288218-31087300-71c7-11eb-8250-c218c1807652.png)

**Operating System:**
 - OS:Windows
 - Version 10

**Comment by EnzoAlbornoz** [comment]
Microsoft login is currently supported only in the beta release channel. Try download the beta release on https://github.com/gorilla-devs/GDLauncher/releases/tag/v1.1.0-beta.2

**Comment by ftzi** [comment]
I've used the beta version and it works fine!

**Comment by Endninja137** [comment]
What's the current status on Microsoft accounts? This part of the launcher has very little documentation for the most recent versions and I want to be sure it works before I commit to installing it.

**Comment by Eskaan** [comment]
They are integrated for quite a while now.

**Comment by EnzoAlbornoz** [comment]
> What's the current status on Microsoft accounts? This part of the launcher has very little documentation for the most recent versions and I want to be sure it works before I commit to installing it.

It's working for most of the players. Microsoft didn't document well the authentication scheme, so most of my findings were from forums.

**Comment by BuckedZulu73825** [comment]
**Describe the bug**
Tried to use the Microsoft account to login to GDLauncher. Does not work

**To Reproduce**
Steps to reproduce the behavior:

1. Click on sign in with Microsoft
2. Enter login Credentials.
3. Finish login
4. Error.


**Expected behavior**
Login success

**Possible solutions**
No idea

Screenshots
<img width="1440" alt="Screenshot 2023-07-19 at 8 47 30 PM" src="https://github.com/gorilla-devs/GDLauncher/assets/140030811/253f105d-d0b9-4f4c-93e5-83452db7e874">

**Operating System:**

- OS:MacOS Ventura
- Version 1.13.1 (a)
