### ISSUE TITLE
Requesting an offline mode for the launcher 

### ISSUE THREAD

**Issue by ankushom19** [gorilla-devs/GDLauncher#838]
It would be great if there was an offline mode in the launcher where we can play mincraft without logging in onto our minecraft accounts xD

**Comment by RemagOfficial** [comment]
wont happen, we dont support piracy

**Comment by ankushom19** [comment]
oh

**Comment by TOLoneWolf** [comment]
> wont happen, we dont support piracy

that is not piracy.  offline play is apart of the vanilla launcher.
![explorer_2WfcbHEWXe](https://user-images.githubusercontent.com/8376628/115155258-ae742680-a044-11eb-805a-220ef2d9ad61.png)

**Comment by RemagOfficial** [comment]
> > wont happen, we dont support piracy
> 
> that is not piracy.  offline play is apart of the vanilla launcher.
> ![explorer_2WfcbHEWXe](https://user-images.githubusercontent.com/8376628/115155258-ae742680-a044-11eb-805a-220ef2d9ad61.png)
> 

they said so we don't have to log in to our accounts, the vanilla launcher still makes you login before allowing offline play

**Comment by megapro17** [comment]
and what's wrong with piracy? you're worrying that some billionaire won't afford another boat?

**Comment by RemagOfficial** [comment]
> and what's wrong with piracy? you're worrying that some billionaire won't afford another boat?

well for a start it's illegal and gdlauncher could run into issues if they allow people to pirate the game.

I'm not saying that piracy is bad in every situation because there are some games that you literally can't buy, for example rollercoaster Tycoon 3 isn't on steam and thus there isn't exactly a way to buy it from the publisher, but I wouldn't encourage people to pirate games unless it's the only option because of bad DRM implementation or the game no longer being sold from its original publisher

**Comment by megapro17** [comment]
> well for a start it's illegal and gdlauncher could run into issues if they allow people to pirate the game.

add it as some hidden way like for debugging purposes. but i'm sure 99.99% noone cares 

> I'm not saying that piracy is bad in every situation

yes, it's not bad in this situation too. microsoft is a very rich corporation, that making money from everything, with not ethical ways too, and downloading one free copy won't hurt at all

**Comment by mottom1** [comment]
Well the problem here is that it is illegal in most parts of the world, and the microsoft would find whoever mad it posible for someone to pirate the game, sue them and take down GDlauncher, which would be very sad.


> yes, it's not bad in this situation too. microsoft is a very rich corporation, that making money from everything, with not ethical ways too, and downloading one free copy won't hurt at all

 And if they did add it to the launcher it would be much more than one copy, much much more.

**Comment by ankushom19** [comment]
Thn why is tlauncher still alive and everyone use it.

**Comment by megapro17** [comment]
> microsoft would find whoever mad it posible for someone to pirate the game, sue them and take down GDlauncher, which would be very sad.

There were ZERO incidents like this. There is launcher in google play that allows to do that and NOBODY cares at all. What nonsense you're saying omg. Piracy doesn't affect profit at all, science research says
**You only making trouble for legal users** who bought the game and wanna quickly login and play, but can't find password, or has problem with internet, etc

**Comment by ankushom19** [comment]
Google play ?

**Comment by huantianad** [comment]
> Piracy doesn't affect profit at all, science research says

Thank you for the well-informed view.

**Comment by mottom1** [comment]
pojlauncer does require an acount, and If others are offering why dont you use theres?

**Comment by megapro17** [comment]
> > Piracy doesn't affect profit at all, science research says
> 
> Thank you for the well-informed view.

Very funny
https://www.engadget.com/2017-09-22-eu-suppressed-study-piracy-no-sales-impact.html
