### ISSUE TITLE
1.1.1 Launcher downloads Forge instead of Fabric for Fabric Curseforge Modpacks

### ISSUE THREAD

**Issue by shaquillerayau** [gorilla-devs/GDLauncher#854]
**Describe the bug**
GDLauncher is installing Forge when installing/downloading a Fabric Modpack

**To Reproduce**
Steps to reproduce the behavior (example):
1. Create a New Instance
2. Download the Curseforge pack "Fabulously Optimised"
3. install and run.

**Expected behavior**
To download the correct version of Forge or Fabric where required. 

**Operating System:**
 - OS: MacOS Catalina

**Comment by dandin87** [comment]
This is not a GD Launcher issue. All Fabric modpacks right now use a mod called jumploader to hijack forge loader to install and run  fabric loader. This is because Curseforge does not currently have Farbic Loader modpack support. They have been working on that, and curseforge should have Fabric Loader support within the next 2 months.
