### ISSUE TITLE
Modpack won't install

### ISSUE THREAD

**Issue by protoelectric** [gorilla-devs/GDLauncher#858]
**Describe the bug**
On the latest version (1.1.1), When installing a modpack from curseforge, It indefinitely does the circling around the name thing.

**To Reproduce**
1. Go to the plus
2. Install any modpack
3. See the error

**Expected behavior**
For the modpack to install

**Possible solutions**
I don't really know

**Screenshots**
None

**Operating System:**
 - OS: Windows 10
 - Version: Lates

**Additional context**
Not sure if it's just me, cause other people can install normally. My friend also has his stuck at 100% on downloading game files.

**Comment by ghost** [comment]
I'm also having this issue hopefully it can get fixed quickly as I've just reinstalled mine and now I can put 90% of my modpacks back on it

**Comment by Grimley4** [comment]
I am having the same issue, I managed to get one modpack loaded but now I am just stuck at that

**Comment by protoelectric** [comment]
I found that it works if you install the latest version.

**Comment by Grimley4** [comment]
I am already on the latest I believe, let me reinstall

**Comment by mackybean** [comment]
On 1.1.1, I can't get it to install any forge modpack, wether it be via importing a zip or selecting it in the modpack browser. and upon trying to check the forge version of any existing modpack, it doesn't show versions, just the Minecraft version itself (Image below in 1.1.1.)
![broken forge](https://user-images.githubusercontent.com/7440439/115842545-ef28c280-a3eb-11eb-9413-06168ed6cfd5.png)

This is replicated in both installed and portable instances. however, upon rolling back to the 1.1.0-Beta2 pre-release, the issue is resolved and everything works as it should, and modpacks install sucsessfully. (image below in 1.1.0-Beta2)
![not broken forge](https://user-images.githubusercontent.com/7440439/115843051-6f4f2800-a3ec-11eb-9721-e31292a34e3e.png)

**Comment by mackybean** [comment]
On 1.1.1, I can't get it to install any forge modpack, wether it be via importing a zip or selecting it in the modpack browser. and upon trying to check the forge version of any existing modpack, it doesn't show versions, just the Minecraft version itself (Image below in 1.1.1.)
![broken forge](https://user-images.githubusercontent.com/7440439/115842545-ef28c280-a3eb-11eb-9413-06168ed6cfd5.png)

This is replicated in both installed and portable instances. however, upon rolling back to the 1.1.0-Beta2 pre-release, the issue is resolved and everything works as it should, and modpacks install sucsessfully. (image below in 1.1.0-Beta2)
![not broken forge](https://user-images.githubusercontent.com/7440439/115843051-6f4f2800-a3ec-11eb-9721-e31292a34e3e.png)

This makes me THINK, it is something in the way the new update is handling looking at the forge repo

**Comment by tomfulghum** [comment]
This is the error i get when trying to install a modpack:

![image](https://user-images.githubusercontent.com/5806810/115865837-283b5400-a439-11eb-9c5a-9f0039b2cdb9.png)
