### ISSUE TITLE
Error with starting an instance

### ISSUE THREAD

**Issue by name** [gorilla-devs/GDLauncher#90]
**Bug details**
I've downloaded the latest release of the launcher and was presented with this error when trying to run the latest version that is recommended me, wondered if I should go back a few releases or this is a new bug that has appeared.

**Screenshot**
![Image of error](https://i.imgur.com/wfrkLLK.png)
![Another image](https://i.imgur.com/FGS78wQ.png)

**Specs**
Windows 10, 64-bit.

**Comment by blarfoon** [comment]
Hello. Thanks for trying out our launcher! In order to solve your issue, I will need some more info.
Can you confirm you have java installed on your system?
### After starting the instance (and the error message has been shown):
In the top left corner of the launcher, there is a "terminal" icon, which will open the launcher console.
Be sure to be in the "console" tab. Then right click below, on the main area and click "save as".
Can you paste here the content of that file?
![image](https://user-images.githubusercontent.com/10165264/45124029-1cf06880-b169-11e8-9cb4-fa456bb03462.png)
![image](https://user-images.githubusercontent.com/10165264/45124064-3ee9eb00-b169-11e8-85bc-319ebafbed6d.png)

**Comment by name** [comment]
Sorry for the late reply, I did some digging and realised I was blocking java from running via another program, sorry to waste any time!
