### ISSUE TITLE
Ram overlap

### ISSUE THREAD

**Issue by NathanPeake** [gorilla-devs/GDLauncher#977]
**Describe the bug**
Ram overlap on the setting menu

**To Reproduce**
get 32gb + ram
go to setting and look at ram

**Expected behavior**
spacing should not allow overlap
**Possible solutions**
fix the spacing

**Screenshots**
![image](https://user-images.githubusercontent.com/37817019/124360530-5780f500-dc22-11eb-8d7d-114ccf384435.png)

**Operating System:**
Windows
21h2
11 pro
os build: 22000.51
Windows Feature Experience Pack 421.16300.0.3

**Additional context**

**Comment by YoYoK3nny** [comment]
Personally, I'd prefer a textbox and a presets dropdown next to it, like with Game Resolution above it.
Otherwise the slider would need either a hardcoded limit or have the stepsize between 16GB and max ram adjust dynamically (ie: first 2 thirds of the slider be 1024MB-16384MB, last third have the values be adjusted dynamically)
