### ISSUE TITLE
Mod downloads skip - not failed modpack installation

### ISSUE THREAD

**Issue by Meister1593** [gorilla-devs/GDLauncher#990]
**Describe the bug**
When downloading mods for modpack (doesnt matter if it's from zip or from curseforge), theres a chance that some mods won't be downloaded at all (by doing 3 retries for 5 seconds).
Currently gdlauncher instead of failing download and overall installation of modpack, it just skips and only merely prints error in logs.
I have discovered this when my friend couldn't download entire modpack and always had less mods than modpack should. Neither me or my other friends didn't have problems installing modpack, it might be related to something specific.
[Related code](https://github.com/gorilla-devs/GDLauncher/blob/7573145eeff6c614a2a73aac121b56238de584a4/src/common/reducers/actions.js#L1654-L1679)

**To Reproduce**
I'm not sure how to reproduce that without having some unstable connection, but in any case it's just matter of downloading any modpack, with exception being unstable, or flawed connection.

**Expected behavior**
Modpack should either download entirely, or not download at all, informing user that something is wrong. 

**Possible solutions**
Write proper retry mechanism, by increasing retry count and maybe lowering timeout time. 
Don't skip failed downloads, but instead fail entire download.

**Operating System:**
 - OS: Friend with that issue is on Windows, but code issues are for sure cross-platform
 - Version: 1.1.11

**Additional info**
Might help a bit, but part of error when mods didn't download might be related to this:
```
connect ECONNREFUSED some-ip
    at TCPConnectWrap.afterConnec
```
Also after 3 downloads of modpack, friend installed all mods successfully

**Comment by jammer312** [comment]
> Don't skip failed downloads, but instead fail entire download.

I don't think it is a good solution, because it might make some modpacks nigh impossible to download. I'm not sure what exactly causes downloads to fail, but I doubt it's because of flawed connection (might it be because of ddos protection from cloudflare (in case of curseforge) or something similar?).
A better solution would be to either remember failed downloads and have an option to try to download these again, or have an option to check modpack integrity and download missing mods.

But yeah, the fact that launcher silently (afaik the only way to notice that mod has failed to download is to open chrome dev tools and go to console section (which is kinda not obvious), because launcher doesn't even print errors to stderr) ignores such errors is not good.
